find_library(COREFOUNDATION_FRAMEWORK CoreFoundation)
if (NOT COREFOUNDATION_FRAMEWORK)
	message(FATAL_ERROR "Could not find CoreFoundation framework.")
endif ()

find_program(Python3_CONFIG_EXECUTABLE python3-config DOC "python3-config executable")

if (NOT Python3_CONFIG_EXECUTABLE)
	message(FATAL_ERROR "Could NOT find python3 config utility.")
endif ()

execute_process(
	COMMAND ${Python3_CONFIG_EXECUTABLE} --include
	OUTPUT_VARIABLE PYTHON_INCLUDE_DIRS
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

string(REPLACE "-I" "" PYTHON_INCLUDE_DIRS "${PYTHON_INCLUDE_DIRS}")
string(REPLACE " " ";" PYTHON_INCLUDE_DIRS "${PYTHON_INCLUDE_DIRS}")


execute_process(
	COMMAND ${Python3_CONFIG_EXECUTABLE} --libs
	OUTPUT_VARIABLE PYTHON_LIBRARIES
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${Python3_CONFIG_EXECUTABLE} --prefix
	OUTPUT_VARIABLE python3_libdir
	OUTPUT_STRIP_TRAILING_WHITESPACE)

string(REPLACE "-framework CoreFoundation" "" PYTHON_LIBRARIES "${PYTHON_LIBRARIES}")
string(REPLACE "-ldl" "" PYTHON_LIBRARIES "${PYTHON_LIBRARIES}")
string(REPLACE "-l" "" PYTHON_LIBRARIES "${PYTHON_LIBRARIES}")
string(REPLACE " " "" PYTHON_LIBRARIES "${PYTHON_LIBRARIES}")

find_library(PYTHON_LIBRARIES ${PYTHON_LIBRARIES} PATHS ${python3_libdir} PATH_SUFFIXES lib NO_DEFAULT_PATH)
set(PYTHON_LIBRARIES "${python3_libdir}/lib/lib${PYTHON_LIBRARIES}.dylib")
set(PYTHON_LIBRARIES ${PYTHON_LIBRARIES} ${COREFOUNDATION_FRAMEWORK} ${CMAKE_DL_LIBS})

message(STATUS ${PYTHON_LIBRARIES})
message(STATUS ${PYTHON_INCLUDE_DIRS})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Python3 
	FOUND_VAR Python3_FOUND
	REQUIRED_VARS PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)