if (APPLE)
    set(claraInstallFolderPrefix "$ENV{HOME}/Library/Application Support/Sublime Text 3")
else()
    set(claraInstallFolderPrefix "$ENV{HOME}/.config/sublime-text-3")
endif()
set(currentSublimePackagesFolder "${claraInstallFolderPrefix}/Packages")
set(claraInstallFolder "${currentSublimePackagesFolder}/Clara")
file(GLOB_RECURSE pycaches RELATIVE "${claraInstallFolder}" *.pyc)
foreach(pycache ${pycaches})
    message(STATUS "Removing python cache file: ${claraInstallFolder}/${pycache}")
    file(REMOVE "${claraInstallFolder}/${pycache}")
endforeach(pycache)
