import sublime, sublime_plugin, os

FILE_NAME = 'C++.sublime-settings'
FILE_CONTENTS = '''// This file was auto-generated by the Clara plugin. You can freely modify it.
{
	"auto_complete_triggers": 
	[
		{
			"selector": "source - (comment, string, constant)", 
			"characters": ".:>"
		}
	]
}
'''

class ClaraWriteAutoCompleteTriggersCommand(sublime_plugin.ApplicationCommand):
	"""Writes a file called C++.sublime-settings to the User directory."""

	def run(self):
		path = os.path.join(sublime.packages_path(), 'User', FILE_NAME)
		if os.path.exists(path):
			if sublime.ok_cancel_dialog('The file\n\n"{}"\n\n already exists. '
				'I will move it to \n\n"{}".\n\n Do you want to continue?'
				.format(path, path + ".backup"), 'Continue'):
				os.rename(path, path + '.backup')
			else:
				return
		with open(path, 'w') as f:
			f.write(FILE_CONTENTS)
		sublime.active_window().run_command('open_file', { "file": path })
